schema: 
  - graphql/schema.graphql
  - graphql/schema.extensions.graphql
documents: graphql/**/*.graphql
extensions:
  codegen:
    generates:
      generated/graphql.ts:
        plugins:
          - typescript
          - typescript-operations
          - typescript-urql
          - typed-document-node
        config:
          scalars:
            JSONString: string
            UUID: string
            Metadata: Record<string, string>
            DateTime: string
      generated/schema.graphql:
        plugins:
          - schema-ast
